# Generated by Django 4.1.4 on 2022-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_trinket_alter_feeding_options_alter_feeding_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="finch",
            name="trinkets",
            field=models.ManyToManyField(to="main_app.trinket"),
        ),
    ]
